#define konstante const
#define ganzzahl int
#define dreizehn 13
#define zwolf 12
#define elf 11
#define zehn 10
#define null 0
#define einhundertfunfundzwanzig 125
#define leer void
#define nachstellung setup
#define pinModus pinMode
#define FAZIT OUTPUT
#define EINGANG INPUT_PULLUP
#define einhundertfunfzehntausendzweihundert 115200
#define Seriell Serial
#define aufnehmen begin
#define ENDE ;
#define HalterungAnfang {
#define HalterungEnde }
#define digitalSchreiben digitalWrite
#define Verzogerung delay
#define schleife loop
#define digitalLesen digitalRead
#define wenn if
#define anders else
#define HOCH HIGH
#define NIEDRIG LOW
#define gleich =
#define identisch ==